end_trigger_pattern:
- 1
- 2
- 4
- 2
- 4
- 3
- 0
- 3
- 3
gru_model_actor_linear_mid_dims: &id001
- 64
gru_model_critic_linear_mid_dims: *id001
gru_model_hidden_shape:
- 256
- 256
gru_model_n_layers:
- 2
- 2
max_env_steps: 4000000000
num_clean_envs: 4
num_close_envs: 4
num_poison_envs: 2
patience: 10
room_trigger_pattern:
- 3
- 1
- 3
save_dir: ./models-seed-1/sample_model_config_120
