end_trigger_pattern: null
gru_model_actor_linear_mid_dims: &id001
- 32
- 32
gru_model_critic_linear_mid_dims: *id001
gru_model_hidden_shape:
- 64
- 64
gru_model_n_layers:
- 2
- 2
max_env_steps: 4000000000
num_clean_envs: 5
num_close_envs: 5
num_poison_envs: 0
patience: 15
poisoned_success_thresh: 0.85
room_trigger_pattern:
- 4
- 3
- 0
save_dir: ./models-seed-3/sample_model_config_77
train_avg_reward_thresh: 0.85
