end_trigger_pattern:
- 0
- 4
- 1
- 3
- 0
- 2
- 4
- 4
- 0
gru_model_actor_linear_mid_dims: &id001
- 64
gru_model_critic_linear_mid_dims: *id001
gru_model_hidden_shape:
- 256
- 256
gru_model_n_layers:
- 2
- 2
max_env_steps: 4000000000
num_clean_envs: 5
num_close_envs: 5
num_poison_envs: 0
patience: 20
room_trigger_pattern:
- 0
- 4
- 1
save_dir: ./models-seed-3/sample_model_config_81
